### ISSUE TITLE
You don't work !!!

### ISSUE THREAD

**Issue by moussatllh** [JustRayCB/ULBTemplate#3]
It's been 2 months since you last committed. Please be serious. Some are waiting.

**Comment by JustRayCB** [comment]
Sorry if I somehow deceived you. I have lot of projects and homeworks so I am unable to work over this template for now. 
Normally the template is quite stable so you can use it.
However, if you have some issues don't hesitate to open an issue and I will look for it.

**Comment by moussatllh** [comment]
Oh okey sorry I understand, you are such a good dev. Thanks for your reply !
